### ISSUE TITLE
Stuck at connecting...

### ISSUE THREAD

**Issue by jackthenewbie** [DomiStyle/docker-tor-browser#45]
Like the title said, I already tried rerun container multiple times, but whenever I connect to tor, it stuck at "Connecting...". 
![image](https://user-images.githubusercontent.com/55600733/220606012-6a974a96-cb9b-4478-9011-ee1e63ccdbea.png)
what could be the reason?

**Comment by azcn2503** [comment]
I am experiencing the same.

I do not see any error log entries.

**Comment by lawndoc** [comment]
I periodically need to close all tabs if I haven't connected for a long time, but that resolves it for me every time. If it doesn't resolve it for you then there's probably something else going on.

**Comment by azcn2503** [comment]
For me this is happening on an x64 system and is the first time using it, so no cache or stale state at play. 

I have tried to restart the container numerous times but it is the same on each restart.

**Comment by lawndoc** [comment]
Just to clarify, restarting the container is not what I meant by closing all of the browser tabs. In the meantime, I'll run a fresh image and see if I can reproduce the issue.

**Comment by lawndoc** [comment]
So far I'm unable to reproduce the issue with the latest x64 image. Can you post the docker run command or compose file you are using with the image? Also, please download a client version of the Tor browser and verify that you can connect to the Tor network through that client (so we can rule out a network block).

**Comment by jackthenewbie** [comment]
> So far I'm unable to reproduce the issue with the latest x64 image. Can you post the docker run command or compose file you are using with the image? Also, please download a [client version](https://www.torproject.org/download/) of the Tor browser and verify that you can connect to Tor from the same network as the docker container (so we can rule out a network/ISP block).
```
tor:
    image: domistyle/tor-browser
    restart: unless-stopped
    environment:
      - VNC_PW=decoy
    #depends_on:
    #  gluetun:
    #    condition: service_started
    volumes:
      - /media/ser3_decoyer/TOSHIBA/downloads/tor:/app/Browser/TorBrowser/Data/Tor
    #network_mode: service:gluetun
    ports:
      - 5880:5800
      - 5881:5900
```
Ye it could really be firewall or something on my machine. I'm currently running linux mint 20. Here's my Tor browser on host. 
![image](https://user-images.githubusercontent.com/55600733/221074725-f8d536f0-2ae3-406f-8dda-f1e826dff461.png)

**Comment by azcn2503** [comment]
> So far I'm unable to reproduce the issue with the latest x64 image. Can you post the docker run command or compose file you are using with the image? Also, please download a [client version](https://www.torproject.org/download/) of the Tor browser and verify that you can connect to Tor from the same network as the docker container (so we can rule out a network/ISP block).

Sure 😄 

Here is my compose config:

```yaml
  tor_browser:
    image: domistyle/tor-browser
    container_name: tor_browser
    environment:
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
      - KEEP_APP_RUNNING=0
      - TZ=Europe/London
      - USER_ID=1000
      - GROUP_ID=1000
      - CONTAINER_DEBUG=1
    ports:
      - 5800:5800
```

It looks like the standalone Tor browser is working on the host (Arch running Linux 6.1.12-arch1-1 with GNOME desktop environment).
